In [5]:
import numpy as np
a = np.arange(6).reshape(2,3)
print(a)
b = a*2
print(b)
a[:,1] = 9
print(a)

[[0 1 2]
 [3 4 5]]
[[ 0  2  4]
 [ 6  8 10]]
[[0 9 2]
 [3 9 5]]


In [ ]:
def add_lists(x: list[int], y: list[int]) -> list[int]:
    return [xi + yi for xi,yi in zip(x,y)]

x = list(range(1_000_000))
y = list(range(1_000_000))

%timeit add_lists(x,y)
%timeit np.add(x,y)

51 ms ± 721 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
